
################################################################################
#
#   DESCRIPTION: LongAIRR config.yaml for snakemake_takara
#      DATASETS: Takara SMARTSEQ (+UMIS) AIRR data [BCR only (or TCR only) /
#                                                   multiplexed samples]
# 
#         Usage: See LongAIRR extended documentation
#
#        AUTHOR: Jonas Schuck, jschuckdev@gmail.com
#    BUG-REPORT: https://github.com/AGImkeller/LongAIRR/issues
#
#          NOTE: When providing file-paths in the `input / output directories 
#                section, please state the **full** paths,
#                starting with the `/home/` directory to required input / output
#                and additional anchor files.
#                Using `~` as an alternative for the /home/ directory or
#                relative paths will possibly result in errors
#
#          NOTE: All stated file-paths are arbitrary examples and need to be set
#                by the user to provide the actual file-paths on the local system
#
################################################################################

#-----longairr filter parameters------------------#
FILTER_MIN_QUAL: 17             # --min-qual:        default: -1 (no quality filtering)
FILTER_MINL: 200                # --minl:            default: -1 (no length filtering)
FILTER_MAXL: 4000               # --maxl:            default: -1 (no length filtering)


#-----longairr demux parameters---------------------------#
DEMUX_WINDOW_LENGTH: 500        # --window-length:   default: 50
DEMUX_MAX_ERROR: 0.2            # --anchor-error:    default: 0.2


#-----longairr collapse parameters--------------------#
COLLAPSE_DEMUX: True                 # --demux:          default: TRUE
COLLAPSE_LIBRARY: "bulk"             # --library:        valid: "bulk" // dont touch

COLLAPSE_WINDOW_LENGTH: 500          # --window-length:  default: 50
COLLAPSE_ANCHOR_ERROR: 0.2           # --anchor-error:   default: 0.2
COLLAPSE_LENGTH: 12                  # --umi-length:     default: 12

COLLAPSE_MINL: -1                    # --minl:           default: -1 (no length filtering)
COLLAPSE_MAXL: -1                    # --maxl:           default: -1 (no length filtering)

COLLAPSE_AF: True                    # --adaptive-filter: default: TRUE                     
COLLAPSE_GROUP_FIELD: "UMI"          # --group-field:     valid: "UMI" (Bulk)
COLLAPSE_AF_MIN_N: 5                 # --filter-min-size: default: 100
COLLAPSE_AF_BIN: 100                 # --bin-size:        default: 100
COLLAPSE_AF_MARGIN: 0.05              # --peak-margin:     default: 0.10

COLLAPSE_CONSGAP: 0.5                # --cons-gap:        default: 0.5
COLLAPSE_CONSERROR: 0.2              # --cons-error:      default: 0.2

COLLAPSE_N_SUBSAMPLE: 750            # --n-subsample:     default: 10000
COLLAPSE_N_CHUNK: 75                 # --n-per-chunk:     default: 50
COLLAPSE_SEED: 1                     # --seed:            default: 1
COLLAPSE_JOBS: 16                     # --cjobs:           default: 6


#-----longairr seqtag parameters----------------#
RUN_SEQTAG: True                 # True | False // snakemake-specific

SEQTAG_SPLIT: False              # --split:          default: FALSE
SEQTAG_WINDOW_LENGTH: 250        # --window-length:  default: 220
SEQTAG_ANCHOR_ERROR: 0.1         # --anchor-error:   default: 0.1
SEQTAG_PRIMER_FIELD: "ISOTYPE"   # --pf:             default: "ISOTYPE"


#-----longairr airr parameters--------------------#
AIRR_PH: True                    # --ph:             default: TRUE
AIRR_LOCUS: "ig"                 # --loci            default: ig // ig: b cell receptor locus


#-------------input / output directories------------------#

################################################################################
# !!!NOTE: When providing file-paths in the `input / output directories 
#                section, please state the **full** paths,
#                starting with the `/home/` directory to required input / output
#                and additional anchor files.
#                Using `~` as an alternative for the /home/ directory or
#                relative paths will possibly result in errors
#
# !!!NOTE: All stated file-paths are arbitrary examples and need to be set
#                by the user to provide the actual file-paths on the local system
################################################################################

#filter
INPUT_DUPLEX_FASTQ: "/home/user123/sampleX/longairr_results/runY/basecalling/simplex_duplex.fastq"    # input_fastq // output from longairr basecall

#demux
DEMUX_UID_FASTA: "/home/user123/path/to/LongAIRR/longairr_example_workflow/example_inputs/required_anchors/bulk_takara/UDI_barcode_rX.fasta"        # demux UDI barcodes_input

#collapse
COLLAPSE_ANCHOR_FASTA: "/home/user123/path/to/LongAIRR/longairr_example_workflow/example_inputs/required_anchors/bulk_takara/UMI_anchor.fasta"           # UMI anchor_seq_input

#seqtag
SEQTAG_FASTA: "/home/user123/path/to/LongAIRR/longairr_example_workflow/example_inputs/required_anchors/bulk_takara/constant_igh_anchors.fasta"                   # isotype_seqs_input

#airr
DATABASES_PARENT: "/home/user123/path/to/databases/"    # parent containing inputdir_igblast and inputdir_germlines (set up during longAIRR installation)

#output directory
OUTPUT: "/home/user123/path/to/longairr_results/"       # outdir


# specify samples (match with IDS in FASTA headers for every UDI-anchor barcode from DEMUX_UID_FASTA)
samples:
  - UID6
  - UID20

#-------------------------misc---------------------------#
# Specify 'True' if you want to copy the used config.yaml to generate the output data into the 'OUTPUT' directory


COPY_CONFIG: True         # snakemake specific

# path to used config.yaml
CONFIG_PATH: "/home/user123/path/to/LongAIRR/longairr_example_workflow/snakemake/takara/config.yaml"

